version: "3.4"
services:
  db:
    image: postgres:14-bullseye
    container_name: swimr_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    container_name: swimr_flyway
    command: -url=jdbc:postgresql://db/postgres -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  api:
    profiles: ["dev"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    depends_on:
      - flyway
    environment:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/postgres?schema=postgres"
volumes:
  db:
