name: Verify Server Unit

on:
  pull_request:
    paths:
      - "swimr-ui/**"

defaults:
  run:
    working-directory: ./swimr-ui

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Test
        run: npm run test
